import{a as b,S as L,i as n}from"./assets/vendor-C2ySes1p.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/",w="55227321-8aa875f9c6bbda7d6f4af2a1c";async function f(s,r){const e={key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await b.get(v,{params:e})).data}const m=document.querySelector(".gallery"),S=new L(".gallery a");function y(s){const r=s.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${e.likes}</p>
          <p><b>Views</b> ${e.views}</p>
          <p><b>Comments</b> ${e.comments}</p>
          <p><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),S.refresh()}function q(){m.innerHTML=""}function p(){document.querySelector(".loader").classList.add("visible")}function h(){document.querySelector(".loader").classList.remove("visible")}function g(){document.querySelector(".load-more").classList.add("visible")}function l(){document.querySelector(".load-more").classList.remove("visible")}let i=1,c="",u=0;const M=document.querySelector(".form"),P=document.querySelector(".load-more");M.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.target.elements.search.value.trim(),!!c){i=1,q(),l(),p();try{const r=await f(c,i);if(u=r.totalHits,r.hits.length===0){n.error({message:"No images found"});return}y(r.hits),Math.ceil(u/15)>1?g():(l(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Error fetching images"})}finally{h()}}});P.addEventListener("click",async()=>{i++,l(),p();try{const s=await f(c,i);y(s.hits);const r=Math.ceil(u/15);i<r?g():(l(),n.info({message:"We're sorry, but you've reached the end of search results."}));const e=document.querySelector(".gallery a");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({message:"Error loading more images"})}finally{h()}});
//# sourceMappingURL=index.js.map
